spring.application.name=Backend


server.port=4040
spring.datasource.url=jdbc:mysql://localhost:3306/atlasstay_db
spring.datasource.username=root
spring.datasource.password=Asdf2001@#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

cloudinary.cloud.name=demk1ru75
cloudinary.api.key=388388576968185
cloudinary.api.secret=zz48QVVSzdKW0xb7hF1epHJeSgg

stripe.secret.key=sk_test_51RMYI0IbgimaQOgcf5AUwlx28jxSGlnzRLaazZoEi8m0rMEWkzmWfxTkZnziYcvN4SrdaGPHyxSqm2or1nUc82wR00gPXWvj2G


jwt.secretKey = eef402e5d03539ae726302d3b12853ce3af45f8f8c48a086008b2024a8873148e0e034d9f1874c2e878b32ec8552785b85757201c58426bf80ea2bb3d577d10a798406c50d4b01fff0b24e5ebd72ff1f4585472545680149e35ab4850b5120464f01419503dafdc3b7663601ca7cc4e66444140b8d1a1814080925d74f9238fe78c0e5be887d86aab4f38c2d77c181831f5c4dcce4d351b65c61a52045c970163118d3e9f1261bda1c2ab91150e4210a9faa4f6842290ff75a959fbf83556318c9672c34fc0fdfda189bc3efcbc90812d3363d9be805ddb80175216af11564fe764d10d5a6954e4678fc7affd9495f1d97623a91ee4b7da8d9538f76b985b628
jwt.expiration= 8640000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=785904721379-0ob3q65sbbf5o2hshct3u0tnokoohufk.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:4040/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email
spring.security.oauth2.client.registration.google.client-name=Google

#spring.mail.host=localhost
#spring.mail.port=1025
#spring.mail.username=karima
#spring.mail.password=karima
#spring.mail.properties.stmp.trust='*'
#spring.mail.properties.auth=true
#spring.mail.properties.sarttls.enabled=true

application.mailing.frontend.activation-url=http://localhost/5173/activate

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lachhebk021@gmail.com
spring.mail.password=brpw hktm qiwk trye
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

